# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'SDCAutoLayout', '~> 2.0.3'
pod 'FDFullscreenPopGesture', '1.1'

